### PR TITLE
Added initial implementation of background env connect

### PR DESCRIPTION
**Pull request by withnale**
**NB: This is a work in progress and the official way to use corectl env is in the foreground until this has stabilised**

This modifies the `corectl env connect` command to include a `-b/--background` flag to allow the proxy to detach and run as a background process. 

To manage these proxies some additional subcommands have been added.

```console
Usage:
  corectl env [flags]
  corectl env [command]

Available Commands:
  active      Show active proxies for environments
  connect     Connect to an environment
  disconnect  Disconnect from an environment
```

The wizard messaging, the logging and the exception handling all need some love (much as they do with other commands). This change has tried as much as possible to minimise the changes to the foreground workflow to allow this to be merged and observed without affecting the main connect workflow.

### CODE REVIEW

**Comment by kkonstan** [comment]
This failure to read file should probably be suppressed:  ```➜  corectl git:(background) ./corectl env connect gcp-dev
2024/11/28 12:49:01 failed to read file /tmp/corectl/gcp-dev.pid: open /tmp/corectl/gcp-dev.pid: no such file or directory
✓ Platform is supported
✓ Configured cluster credentials: project=core-platform-efb3c84c zone=europe-west2 cluster=gcp-dev
✓ Kubernetes config context set to: gke_core-platform-efb3c84c_europe-west2_gcp-dev
✓ Kubernetes proxy url set to: localhost:37026
✓ IAP connection succeeded
✓ Bound to localhost:37026
```

**Comment by kkonstan** [comment]
Ideally the connect/disconnect should be idempotent so they can be easily used in scripts.

disconnect is fine: 
```
➜  corectl git:(background) ./corectl env disconnect gcp-dev
Active proxies:
2024/11/28 12:54:12 removing pid file /tmp/corectl/gcp-dev.pid for pid 87713
[gcp-dev] killed process 87713 on port 61110
➜  corectl git:(background) ./corectl env disconnect gcp-dev
Active proxies:
➜  corectl git:(background) 
```
connect however will return error if a tunnel already exists:
```
➜  corectl git:(background) ./corectl env connect gcp-dev --background
2024/11/28 12:54:49 failed to read file /tmp/corectl/gcp-dev.pid: open /tmp/corectl/gcp-dev.pid: no such file or directory
✓ Platform is supported
✓ Configured cluster credentials: project=core-platform-efb3c84c zone=europe-west2 cluster=gcp-dev
✓ Kubernetes config context set to: gke_core-platform-efb3c84c_europe-west2_gcp-dev
✓ Kubernetes proxy url set to: localhost:37026
✓ IAP connection succeeded
✓ Bound to localhost:37026
✓ Process started for gcp-dev in background with PID 88045
➜  corectl git:(background) ./corectl env connect gcp-dev --background
Error: connection already exists for environment gcp-dev with pid 88045
➜  corectl git:(background) 
```
As per the ticket it should only return an error if a tunnel couldn't be established, in this case there is one and doesn't need to be established, so I'd argue that it shouldn't be returning an error.

**Comment by withnale** [comment]
Pushed some changes.

**Review by tmcalves — APPROVED** [review]

**Comment by kkonstan** [comment]
Please note I had to squash and resign commits to get it merged

**Pull request merged**
